name: CD Pipeline

on:
  push:
    branches:
      - main
      - dbc

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dbc'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to DEV server"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD server"
